# Generated by Django 3.2.9 on 2021-12-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.CharField(max_length=200)),
                ('host_port', models.IntegerField(max_length=5)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('log_position', models.CharField(max_length=500)),
            ],
        ),
    ]
