# Generated by Django 3.2.9 on 2021-12-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loganalyzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socketlog',
            name='host_port',
            field=models.IntegerField(),
        ),
    ]
