# Generated by Django 3.2.9 on 2021-12-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loganalyzes', '0002_alter_socketlog_host_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='socketlog',
            name='log_save_position',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
